# Generated by Django 5.1.3 on 2024-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fach',
            name='genau_richtig',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fach',
            name='zu_hoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fach',
            name='zu_niedrig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fach',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
